export const grammarTopicsData: Record<string, { title: string; content: string[] }> = {
    nouns: {
        title: "Nouns",
        content: [
            "🌟 What is a Noun? (In Easy English)",
            "A noun is a word that names something. It can be the name of a person, place, thing, or idea.",
            "👉 You can touch, see, feel, or think about the thing a noun describes.",
            "Examples:",
            "Person: teacher, Ali, doctor",
            "Place: school, Pakistan, market",
            "Thing: book, apple, pen",
            "Idea: love, happiness, honesty",
            "🔹 Types of Nouns",
            "Let’s understand the main types of nouns one by one:",
            "1. Common Noun",
            "It is a general name of a person, place, or thing.",
            "It does not start with a capital letter (unless it comes at the beginning of a sentence).",
            "Examples: boy, girl, city, car, fruit",
            "2. Proper Noun",
            "It is a special name of a person, place, or thing.",
            "It always starts with a capital letter.",
            "Examples: Waqar, Lahore, Toyota, Quran",
            "3. Concrete Noun",
            "These are nouns you can see, touch, taste, hear, or smell.",
            "Examples: apple, chair, dog, music",
            "4. Abstract Noun",
            "These are ideas or feelings. You cannot see or touch them.",
            "Examples: happiness, anger, bravery, knowledge",
            "5. Collective Noun",
            "It is a word for a group of people or things.",
            "Examples: team (group of players), class (group of students), flock (group of birds)",
            "6. Countable Noun",
            "Nouns you can count.",
            "Examples: apples, books, pens",
            "7. Uncountable Noun",
            "Nouns you cannot count easily.",
            "Examples: milk, sugar, water, air",
            "🧠 Examples in Sentences",
            "My teacher gave me a book. (Common Nouns)",
            "Ali lives in Karachi. (Proper Nouns)",
            "She showed great kindness to the poor. (Abstract Noun)",
            "The team won the match. (Collective Noun)",
            "I bought three mangoes. (Countable Noun)",
            "I drank a glass of milk. (Uncountable Noun)",
            "🎯 How to Identify a Noun",
            "Ask these questions:",
            "What is it?",
            "Who is it?",
            "Where is it?",
            "Example: “The dog is barking.” 👉 What is barking? → dog → noun",
            "📚 Noun and Grammar Rules",
            "1. Plural Nouns: When there is more than one, we often add s or es.",
            "Examples: one cat → two cats, one box → two boxes",
            "2. Possessive Nouns: They show ownership or belonging by adding ’s or just ’.",
            "Examples: Waqar’s book (the book belongs to Waqar), Girls’ room (the room belongs to girls)",
            "3. Noun as Subject: The noun does the action.",
            "Example: Ali plays football. 👉 Ali is the subject of the sentence.",
            "4. Noun as Object: The noun receives the action.",
            "Example: She reads a book. 👉 Book is the object.",
            "🪄 Tips to Remember",
            "✅ Nouns name things.",
            "✅ They can be common or proper, countable or uncountable, abstract or concrete.",
            "✅ A noun can be a subject, object, or possessive in a sentence.",
            "🧩 Noun Quiz (Practice Yourself)",
            "Identify the nouns: “My brother loves music.”",
            "Which type of noun is “Karachi”?",
            "Is “milk” countable or uncountable?",
            "Which is the abstract noun in this sentence: “Honesty is important.”",
            "✨ Conclusion",
            "Nouns are very important in English. Every sentence you speak or write usually has a noun. Once you understand nouns, your English will improve fast! 🗣️"
        ]
    },
    // Add "pronouns", "verbs", etc. here later
};
