import type { Ministry } from "./types";

export const communications: Ministry = {
    name: "Ministry of Communications",
    slug: "communications",
    departments: [
        {
            name: "Pakistan Post",
            slug: "pakistan-post",
            type: "Department",
            posts: [
                { bs: "22", postName: "Director General", qualification: "Master’s degree", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Director General (Operations)", qualification: "Master’s degree", ageLimit: "30–50" },
                { bs: "20", postName: "Director (Policy & Planning)", qualification: "Master’s degree", ageLimit: "30–50" },
                { bs: "18", postName: "Deputy Director (Administration)", qualification: "Bachelor’s degree; 2 yrs exp", ageLimit: "25–45" },
                { bs: "17", postName: "Assistant Director (Finance)", qualification: "Bachelor’s degree in Accounting", ageLimit: "25–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "National Highway Authority (NHA)",
            slug: "nha",
            type: "Authority",
            posts: [
                { bs: "22", postName: "Chairman", qualification: "Master’s degree; PAS officer", ageLimit: "35–55" },
                { bs: "21", postName: "Member (Operations)", qualification: "Master’s degree; 5 yrs exp", ageLimit: "30–50" },
                { bs: "21", postName: "Member (Planning & Dev)", qualification: "Master’s degree", ageLimit: "30–50" },
                { bs: "19", postName: "Director Engineer", qualification: "Ph.D/MSc in Civil Engineering", ageLimit: "30–50" },
                { bs: "18", postName: "Deputy Director Engineer", qualification: "MSc/BSc in Civil Engineering", ageLimit: "25–45" },
                { bs: "17", postName: "Assistant Director Engineer", qualification: "MSc/BSc in Civil Engineering", ageLimit: "25–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Senior Assistant (SAC)", qualification: "I.Com/D.Com/FA", ageLimit: "18–30" },
                { bs: "05", postName: "Electrician", qualification: "Electrician certificate", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "National Transport Research Centre (NTRC)",
            slug: "ntrc",
            type: "Centre",
            posts: [
                { bs: "21", postName: "Executive Director", qualification: "Master’s degree (Transport Planning)", ageLimit: "35–55" },
                { bs: "19", postName: "Deputy Director (Research)", qualification: "Master’s degree (Transport Engineering)", ageLimit: "30–45" },
                { bs: "18", postName: "Deputy Director (Administration)", qualification: "Bachelor’s degree; 2 yrs exp", ageLimit: "25–45" },
                { bs: "17", postName: "Assistant Director (Data Analysis)", qualification: "Bachelor’s degree; 2 yrs exp", ageLimit: "25–35" },
                { bs: "16", postName: "Research Officer", qualification: "Bachelor’s degree in relevant field", ageLimit: "21–30" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "Construction Technology Training Institute (CTTI)",
            slug: "ctti",
            type: "Institute",
            posts: [
                { bs: "19", postName: "Principal", qualification: "Master’s degree (Engineering)", ageLimit: "35–55" },
                { bs: "18", postName: "Deputy Director (Training)", qualification: "Bachelor’s degree; 2 yrs exp", ageLimit: "25–45" },
                { bs: "17", postName: "Assistant Director (Instruction)", qualification: "Bachelor’s degree; 2 yrs exp", ageLimit: "25–35" },
                { bs: "16", postName: "Training Officer", qualification: "Bachelor’s degree in relevant trade", ageLimit: "21–30" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
    ],
};
