import type { Ministry } from "./types";

export const defenceProduction: Ministry = {
    name: "Ministry of Defence Production",
    slug: "defence-production",
    departments: [
        {
            name: "Pakistan Ordnance Factories (POF)",
            slug: "pof",
            type: "Factory",
            posts: [
                { bs: "22", postName: "Chairman, POF Board", qualification: "Lieutenant General (Retd.)", ageLimit: "35–60" },
                { bs: "21", postName: "Director General", qualification: "Master’s degree", ageLimit: "35–55" },
                { bs: "20", postName: "Works Manager", qualification: "BSc Engineering", ageLimit: "28–50" },
                { bs: "19", postName: "Executive Engineer", qualification: "BSc Engineering", ageLimit: "25–45" },
                { bs: "18", postName: "Deputy Works Manager", qualification: "BSc Engineering", ageLimit: "25–40" },
                { bs: "17", postName: "Assistant Works Manager", qualification: "Diploma/BSc Engineering", ageLimit: "21–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "Heavy Industries Taxila (HIT)",
            slug: "hit",
            type: "Industry",
            posts: [
                { bs: "21", postName: "Managing Director", qualification: "Master’s degree; PAS officer", ageLimit: "35–55" },
                { bs: "20", postName: "General Manager", qualification: "Master’s degree; 5 yrs exp", ageLimit: "30–50" },
                { bs: "19", postName: "Chief Engineer", qualification: "BSc Engineering", ageLimit: "30–50" },
                { bs: "18", postName: "Deputy Chief Engineer", qualification: "BSc Engineering", ageLimit: "25–45" },
                { bs: "17", postName: "Senior Engineer", qualification: "BSc Engineering", ageLimit: "25–40" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "Pakistan Aeronautical Complex (PAC)",
            slug: "pac",
            type: "Complex",
            posts: [
                { bs: "22", postName: "Chairman", qualification: "Air Vice Marshal rank", ageLimit: "35–55" },
                { bs: "21", postName: "Managing Director", qualification: "Master’s degree; 5 yrs exp", ageLimit: "30–50" },
                { bs: "20", postName: "Chief Financial Officer", qualification: "Master’s degree in Finance", ageLimit: "30–50" },
                { bs: "19", postName: "Chief Engineer", qualification: "BSc Engineering", ageLimit: "30–50" },
                { bs: "18", postName: "Deputy Director (Production)", qualification: "BSc Engineering", ageLimit: "25–45" },
                { bs: "17", postName: "Assistant Director (Quality Control)", qualification: "BSc Engineering", ageLimit: "25–40" },
                { bs: "16", postName: "Scientific Officer", qualification: "Master’s degree (Science)", ageLimit: "21–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "Karachi Shipyard & Engineering Works",
            slug: "karachi-shipyard",
            type: "Shipyard",
            posts: [
                { bs: "22", postName: "Chairman, Board of Directors", qualification: "Chief of Naval Staff", ageLimit: "35–60" },
                { bs: "21", postName: "Managing Director", qualification: "Master’s degree; 5 yrs exp", ageLimit: "30–50" },
                { bs: "20", postName: "Director Finance", qualification: "Master’s degree in Finance", ageLimit: "30–50" },
                { bs: "19", postName: "Project Director (Submarine Construction)", qualification: "BSc Engineering", ageLimit: "30–50" },
                { bs: "18", postName: "General Manager (Ship Building)", qualification: "BSc Mechanical/Civil Engineering", ageLimit: "30–45" },
                { bs: "17", postName: "General Manager (Ship Repair)", qualification: "Diploma in Engineering", ageLimit: "25–40" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 40 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
    ],
};
