import type { Ministry } from "./types";

export const defence: Ministry = {
    name: "Ministry of Defence",
    slug: "defence",
    departments: [
        {
            name: "Pakistan Army",
            slug: "pakistan-army",
            type: "Armed Force",
            posts: [
                { bs: "22", postName: "Chief of Army Staff (General)", qualification: "PMA graduate, Commissioned Officer", ageLimit: "40–60" },
                { bs: "21", postName: "Lieutenant General", qualification: "Commissioned Officer", ageLimit: "40–55" },
                { bs: "20", postName: "Major General", qualification: "Commissioned Officer", ageLimit: "35–50" },
                { bs: "19", postName: "Brigadier", qualification: "Commissioned Officer", ageLimit: "35–45" },
                { bs: "18", postName: "Colonel", qualification: "Commissioned Officer", ageLimit: "30–40" },
                { bs: "17", postName: "Lieutenant Colonel", qualification: "Commissioned Officer", ageLimit: "25–35" },
                { bs: "16", postName: "Major", qualification: "Commissioned Officer", ageLimit: "23–30" },
                { bs: "15", postName: "Captain", qualification: "Commissioned Officer", ageLimit: "22–28" },
                { bs: "14", postName: "Lieutenant", qualification: "Commissioned Officer", ageLimit: "21–25" },
                { bs: "13", postName: "Second Lieutenant", qualification: "Commissioned Officer", ageLimit: "18–23" },
            ],
        },
        {
            name: "Pakistan Navy",
            slug: "pakistan-navy",
            type: "Armed Force",
            posts: [
                { bs: "22", postName: "Chief of Naval Staff (Admiral)", qualification: "Naval Academy graduate, Commissioned Officer", ageLimit: "40–60" },
                { bs: "21", postName: "Vice Admiral", qualification: "Commissioned Officer", ageLimit: "40–55" },
                { bs: "20", postName: "Rear Admiral", qualification: "Commissioned Officer", ageLimit: "35–50" },
                { bs: "19", postName: "Commodore", qualification: "Commissioned Officer", ageLimit: "35–45" },
                { bs: "18", postName: "Captain", qualification: "Commissioned Officer", ageLimit: "30–40" },
                { bs: "17", postName: "Commander", qualification: "Commissioned Officer", ageLimit: "28–35" },
                { bs: "16", postName: "Lieutenant Commander", qualification: "Commissioned Officer", ageLimit: "25–32" },
                { bs: "15", postName: "Lieutenant", qualification: "Commissioned Officer", ageLimit: "23–28" },
                { bs: "14", postName: "Sub Lieutenant", qualification: "Commissioned Officer", ageLimit: "18–24" },
                { bs: "13", postName: "Midshipman", qualification: "Officer Cadet", ageLimit: "18–22" },
            ],
        },
        {
            name: "Pakistan Air Force",
            slug: "pakistan-air-force",
            type: "Armed Force",
            posts: [
                { bs: "22", postName: "Chief of Air Staff (Air Chief Marshal)", qualification: "PAF Academy graduate, Commissioned Officer", ageLimit: "40–60" },
                { bs: "21", postName: "Air Marshal", qualification: "Commissioned Officer", ageLimit: "40–55" },
                { bs: "20", postName: "Air Vice-Marshal", qualification: "Commissioned Officer", ageLimit: "35–50" },
                { bs: "19", postName: "Air Commodore", qualification: "Commissioned Officer", ageLimit: "35–45" },
                { bs: "18", postName: "Group Captain", qualification: "Commissioned Officer", ageLimit: "30–40" },
                { bs: "17", postName: "Wing Commander", qualification: "Commissioned Officer", ageLimit: "28–35" },
                { bs: "16", postName: "Squadron Leader", qualification: "Commissioned Officer", ageLimit: "25–32" },
                { bs: "15", postName: "Flight Lieutenant", qualification: "Commissioned Officer", ageLimit: "23–28" },
                { bs: "14", postName: "Flying Officer", qualification: "Commissioned Officer", ageLimit: "21–24" },
                { bs: "13", postName: "Pilot Officer", qualification: "Officer Cadet", ageLimit: "18–22" },
            ],
        },
        {
            name: "Military Lands & Cantonments",
            slug: "mlc",
            type: "Department",
            posts: [
                { bs: "20", postName: "Director General", qualification: "BS-20 civil post (Major General appointment)", ageLimit: "40–60" },
                { bs: "19", postName: "Additional Director General", qualification: "BS-19 civil post", ageLimit: "35–55" },
                { bs: "18", postName: "Regional Director", qualification: "BS-18 civil post", ageLimit: "30–50" },
                { bs: "17", postName: "Deputy Director", qualification: "BS-17 civil post", ageLimit: "25–40" },
                { bs: "16", postName: "Section Officer", qualification: "BS-16 civil post", ageLimit: "25–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; 40 wpm typing", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; 30 wpm typing", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
        {
            name: "Defence Division",
            slug: "defence-division",
            type: "Division",
            posts: [
                { bs: "22", postName: "Secretary Defence", qualification: "PAS officer (BS-22)", ageLimit: "45–60" },
                { bs: "21", postName: "Additional Secretary", qualification: "PAS officer (BS-21)", ageLimit: "40–55" },
                { bs: "20", postName: "Joint Secretary", qualification: "CSS officer (BS-20)", ageLimit: "35–50" },
                { bs: "19", postName: "Deputy Secretary", qualification: "CSS officer (BS-19)", ageLimit: "30–45" },
                { bs: "18", postName: "Under Secretary", qualification: "CSS officer (BS-18)", ageLimit: "28–40" },
                { bs: "17", postName: "Section Officer", qualification: "BS-17 civil post", ageLimit: "25–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; 40 wpm typing", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; 30 wpm typing", ageLimit: "18–30" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid LTV licence", ageLimit: "18–30" },
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
            ],
        },
    ],
};
