import type { Ministry } from "./types";

export const finance: Ministry = {
    name: "Ministry of Finance & Revenue",
    slug: "finance",
    departments: [
        {
            name: "Federal Board of Revenue (FBR)",
            slug: "fbr",
            type: "Authority",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "03", postName: "Mali (Gardener)", qualification: "Primary pass", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid Driving licence", ageLimit: "18–35 (incl. 5 yr relaxation)" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "07", postName: "Dispatch Rider", qualification: "Primary pass; motorcycle licence", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; 30 wpm typing", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "10", postName: "Tax Assistant", qualification: "Intermediate; bookkeeping", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; 30 wpm typing; Basic IT course", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "12", postName: "Audit Assistant", qualification: "Intermediate; basic accounting", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "13", postName: "Junior Auditor", qualification: "Bachelor’s in Commerce", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate; shorthand & 40 wpm typing", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "15", postName: "Personal Assistant", qualification: "Bachelor’s degree", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "16", postName: "Inspector Inland Revenue", qualification: "Bachelor’s degree", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "17", postName: "Assistant Commissioner Inland Revenue", qualification: "Master’s degree", ageLimit: "21–30" },
                { bs: "18", postName: "Deputy Commissioner Inland Revenue", qualification: "Master’s degree + relevant experience", ageLimit: "25–35" },
                { bs: "19", postName: "Commissioner Inland Revenue", qualification: "Master’s + senior service", ageLimit: "30–45" },
                { bs: "20", postName: "Member FBR", qualification: "Federal Secretariat grade", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Member FBR", qualification: "Head of cadre", ageLimit: "40–60" },
                { bs: "22", postName: "Chairman FBR", qualification: "Federal Secretary grade", ageLimit: "45–65" },
            ],
        },
        {
            name: "Securities and Exchange Commission of Pakistan (SECP)",
            slug: "secp",
            type: "Commission",
            posts: [
                { bs: "05", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "07", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate; shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Audit Officer", qualification: "Bachelor’s in Commerce/Finance", ageLimit: "21–30" },
                { bs: "12", postName: "Network Administrator", qualification: "Bachelor’s in CS/IT", ageLimit: "21–30" },
                { bs: "13", postName: "Research Analyst", qualification: "Bachelor’s/Master’s in Economics/Finance", ageLimit: "21–30" },
                { bs: "14", postName: "IT Officer", qualification: "Bachelor’s in CS/IT", ageLimit: "21–30" },
                { bs: "15", postName: "Assistant Manager", qualification: "Master’s in Business/Finance", ageLimit: "25–35" },
                { bs: "16", postName: "Manager", qualification: "Master’s + experience", ageLimit: "28–40" },
                { bs: "17", postName: "Assistant Director (PMU)", qualification: "Master’s (16 yrs)", ageLimit: "≤35" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + relevant experience", ageLimit: "30–45" },
                { bs: "19", postName: "Commissioner", qualification: "Master’s; 20 yrs post-qual experience", ageLimit: "≤62" },
                { bs: "20", postName: "Member SECP", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "21", postName: "Additional Member SECP", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "22", postName: "Chairman SECP", qualification: "Federal Secretary grade", ageLimit: "45–65" },
            ],
        },
        {
            name: "State Bank of Pakistan (SBP)",
            slug: "sbp",
            type: "Central Bank",
            posts: [
                { bs: "SBOTS-17", postName: "Assistant Director (Officers Training)", qualification: "Bachelor’s/Master’s (16 yrs)", ageLimit: "≤26 (relaxable)" },
                { bs: "OG-3", postName: "Economist (Grade-III)", qualification: "Master’s in Economics", ageLimit: "≤35" },
                { bs: "OG-2", postName: "System Administrator", qualification: "Bachelor’s (16 yrs) in CS", ageLimit: "≤32" },
            ],
        },
        {
            name: "Economic Affairs Division",
            slug: "economic-affairs-division",
            type: "Division",
            posts: [
                { bs: "05", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "06", postName: "Stenotypist", qualification: "Intermediate; shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "07", postName: "Data Entry Operator", qualification: "Intermediate; 30 wpm typing", ageLimit: "18–30" },
                { bs: "08", postName: "Audit Assistant", qualification: "Intermediate; bookkeeping", ageLimit: "18–30" },
                { bs: "09", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "10", postName: "Accountant", qualification: "Bachelor’s in Commerce", ageLimit: "21–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "12", postName: "Audit Officer", qualification: "Bachelor’s in Commerce/Finance", ageLimit: "21–30" },
                { bs: "13", postName: "Assistant Economist", qualification: "Master’s in Economics/Finance", ageLimit: "21–30" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate; shorthand & typing", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "15", postName: "Assistant Economic Analyst", qualification: "Master’s in Economics", ageLimit: "25–35" },
                { bs: "16", postName: "Auditor", qualification: "Bachelor’s in Commerce", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "17", postName: "Assistant Economic Adviser", qualification: "Master’s in Economics/Finance", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + relevant experience", ageLimit: "28–40" },
                { bs: "19", postName: "Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "20", postName: "Joint Secretary (Economic Affairs)", qualification: "Federal Secretariat grade", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–60" },
                { bs: "22", postName: "Secretary, Economic Affairs", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Budget Wing",
            slug: "budget-wing",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "06", postName: "Stenotypist", qualification: "Intermediate; shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "07", postName: "Data Entry Operator", qualification: "Intermediate; 30 wpm typing", ageLimit: "18–30" },
                { bs: "08", postName: "Accounts Assistant", qualification: "Bachelor’s in Commerce", ageLimit: "21–30" },
                { bs: "09", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "10", postName: "Budget Assistant", qualification: "Bachelor’s in Finance/Public Admin", ageLimit: "21–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "12", postName: "Audit Officer", qualification: "Bachelor’s in Commerce/Finance", ageLimit: "21–30" },
                { bs: "13", postName: "Budget Analyst", qualification: "Master’s in Public Admin/Finance", ageLimit: "25–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate; shorthand & typing", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "15", postName: "Assistant Budget Analyst", qualification: "Bachelor’s degree", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "16", postName: "Deputy Budget Officer", qualification: "Master’s in Public Admin/Finance", ageLimit: "25–35" },
                { bs: "17", postName: "Budget Officer", qualification: "Master’s in Public Admin/Finance", ageLimit: "18–30 (incl. 5 yr relaxation)" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + experience", ageLimit: "28–40" },
                { bs: "19", postName: "Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "20", postName: "Joint Secretary (Budget)", qualification: "Federal Secretariat grade", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–60" },
                { bs: "22", postName: "Secretary, Finance & Revenue", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
    ],
};
