import type { Ministry } from "./types";

export const healthServices: Ministry = {
    name: "Ministry of National Health Services, Regulations & Coordination",
    slug: "health-services",
    departments: [
        {
            name: "National Institute of Health (NIH)",
            slug: "nih",
            type: "Institute",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "14", postName: "Laboratory Assistant / Technician", qualification: "Matric + Diploma in Medical Lab Technology", ageLimit: "18–30" },
                { bs: "16", postName: "Scientific Officer", qualification: "M.Sc (Hons) in relevant discipline", ageLimit: "32 years" },
                { bs: "17", postName: "Deputy Director (Technical)", qualification: "Master’s + 2 yrs post-qualification experience", ageLimit: "25–35" },
                { bs: "18", postName: "Director (Technical)", qualification: "Master’s + 5 yrs experience", ageLimit: "28–40" },
                { bs: "19", postName: "Additional Director", qualification: "Master’s + senior service record", ageLimit: "30–50" },
                { bs: "20", postName: "Joint Director", qualification: "Senior service", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Director General", qualification: "Top management grade", ageLimit: "40–60" },
                { bs: "22", postName: "Director General", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Drug Regulatory Authority of Pakistan (DRAP)",
            slug: "drap",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Assistant Director", qualification: "Bachelor’s in Pharmacy / Science", ageLimit: "22–30" },
                { bs: "16", postName: "Drug Inspector", qualification: "Pharm. D / D.Pharm", ageLimit: "30 years" },
                { bs: "17", postName: "Senior Drug Inspector", qualification: "Pharm. D + 2 yrs experience", ageLimit: "32 years" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s in relevant field", ageLimit: "35 years" },
                { bs: "19", postName: "Director", qualification: "Senior service", ageLimit: "38 years" },
                { bs: "20", postName: "Joint Director General", qualification: "Top management grade", ageLimit: "40 years" },
                { bs: "21", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "45 years" },
                { bs: "22", postName: "Director General", qualification: "Head of Authority", ageLimit: "50 years" },
            ],
        },
        {
            name: "Expanded Programme on Immunization (EPI)",
            slug: "epi",
            type: "Programme",
            posts: [
                { bs: "05", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "06", postName: "Vaccinator", qualification: "Matric + Vaccination certificate", ageLimit: "18–30" },
                { bs: "11", postName: "Programme Assistant", qualification: "Bachelor’s degree", ageLimit: "22–30" },
                { bs: "18", postName: "Programme Manager", qualification: "Master’s in Public Health", ageLimit: "35 years" },
                { bs: "19", postName: "Deputy Director (Immunization)", qualification: "Master’s + relevant experience", ageLimit: "38 years" },
                { bs: "20", postName: "Director (Immunization)", qualification: "Senior service", ageLimit: "40 years" },
                { bs: "21", postName: "Additional Secretary (Health)", qualification: "Top cadre", ageLimit: "45 years" },
                { bs: "22", postName: "Secretary, NHSR&C", qualification: "Federal Secretary grade", ageLimit: "50–60 years" },
            ],
        },
        {
            name: "Pakistan Nursing Council (PNC)",
            slug: "pnc",
            type: "Council",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Accounts Assistant / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "16", postName: "Charge Nurse", qualification: "B.Sc Nursing / Diploma + valid PNC registration", ageLimit: "21–28" },
                { bs: "17", postName: "Nursing Instructor", qualification: "M.Sc Nursing / Post-RN BSN", ageLimit: "25–35" },
                { bs: "18", postName: "Curriculum Officer", qualification: "Master’s in Education / Nursing", ageLimit: "30–40" },
                { bs: "19", postName: "Deputy Director", qualification: "Master’s + senior service", ageLimit: "35–50" },
                { bs: "20", postName: "Director", qualification: "Senior management grade", ageLimit: "40–55" },
                { bs: "21", postName: "Additional Registrar", qualification: "Top cadre", ageLimit: "45–60" },
                { bs: "22", postName: "Registrar", qualification: "Head of Council", ageLimit: "50–65" },
            ],
        },
    ],
};
