import type { Ministry } from "./types";

export const housingWorks: Ministry = {
    name: "Ministry of Housing & Works",
    slug: "housing-works",
    departments: [
        {
            name: "Pakistan Housing Authority Foundation (PHA)",
            slug: "pha",
            type: "Foundation",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Accounts Officer", qualification: "Bachelor’s in Commerce / Economics", ageLimit: "18–30" },
                { bs: "16", postName: "Assistant Architect", qualification: "Bachelor’s in Architecture", ageLimit: "25–35" },
                { bs: "17", postName: "Planning Assistant", qualification: "Master’s in City / Regional Planning", ageLimit: "25–35" },
                { bs: "18", postName: "Assistant Director (Architectural)", qualification: "Master’s in Architecture; 2 yrs experience", ageLimit: "28–40" },
                { bs: "19", postName: "Deputy Director (Planning)", qualification: "Master’s + 5 yrs experience", ageLimit: "30–45" },
                { bs: "20", postName: "Director (Projects)", qualification: "Senior management grade", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Secretary (Works)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "22", postName: "Secretary, Housing & Works", qualification: "Federal Secretary grade", ageLimit: "45–65" },
            ],
        },
        {
            name: "Federal Government Employees Housing Authority (FGEHA)",
            slug: "fgeha",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Peon / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "14", postName: "Estate Officer", qualification: "Bachelor’s in Civil Engineering / Architecture", ageLimit: "22–30" },
                { bs: "16", postName: "Assistant Director (Estate)", qualification: "Master’s + 2 yrs relevant experience", ageLimit: "25–35" },
                { bs: "17", postName: "Deputy Director (Estate)", qualification: "Master’s + 5 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Director (Estate Management)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Joint Secretary (Housing)", qualification: "Federal Secretariat grade", ageLimit: "35–55" },
                { bs: "20", postName: "Additional Secretary (Housing)", qualification: "Top management grade", ageLimit: "40–60" },
                { bs: "21", postName: "Federal Secretary (Works)", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "22", postName: "Chairman, FGEHA", qualification: "Federal Secretary equivalent", ageLimit: "50–65" },
            ],
        },
        {
            name: "Public Works Department (PWD)",
            slug: "pwd",
            type: "Department",
            posts: [
                { bs: "05", postName: "Chowkidar / Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Draftsman", qualification: "Diploma in Civil Draftsmanship", ageLimit: "18–30" },
                { bs: "16", postName: "Sub-Engineer (Civil)", qualification: "Diploma in Civil Engineering", ageLimit: "22–30" },
                { bs: "17", postName: "Assistant Engineer", qualification: "B.Sc in Civil Engineering", ageLimit: "25–35" },
                { bs: "18", postName: "Executive Engineer", qualification: "B.Sc + 5 yrs experience", ageLimit: "28–45" },
                { bs: "19", postName: "Superintending Engineer", qualification: "Senior Civil Engineer", ageLimit: "30–50" },
                { bs: "20", postName: "Chief Engineer", qualification: "Chief cadre Civil Engineer", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Secretary (PWD)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "22", postName: "Director General (PWD)", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
    ],
};
