import type { Ministry } from "./types";

export const humanRights: Ministry = {
    name: "Ministry of Human Rights",
    slug: "human-rights",
    departments: [
        {
            name: "National Commission for Human Rights (NCHR)",
            slug: "nchr",
            type: "Commission",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Research Assistant", qualification: "Bachelor’s in Social Sciences or Law", ageLimit: "22–30" },
                { bs: "16", postName: "Program Officer", qualification: "Master’s in Human Rights / Social Sciences", ageLimit: "25–35" },
                { bs: "17", postName: "Assistant Director (Programs)", qualification: "Master’s + 2 yrs relevant experience", ageLimit: "28–35" },
                { bs: "18", postName: "Deputy Director (Investigation)", qualification: "Master’s + 5 yrs experience", ageLimit: "30–40" },
                { bs: "19", postName: "Director (Legal Affairs)", qualification: "LLB + 5 yrs post-qualification experience", ageLimit: "30–45" },
                { bs: "20", postName: "Joint Secretary (Human Rights)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "National Commission on the Status of Women (NCSW)",
            slug: "ncsw",
            type: "Commission",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "14", postName: "Research Assistant", qualification: "Bachelor’s in Gender Studies / Social Sciences", ageLimit: "22–30" },
                { bs: "16", postName: "Policy Officer", qualification: "Master’s in Public Policy / Gender Studies", ageLimit: "25–35" },
                { bs: "17", postName: "Assistant Director (Policy)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–35" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + 5 yrs experience", ageLimit: "30–45" },
                { bs: "19", postName: "Director", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "20", postName: "Joint Secretary", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "National Child Protection Centre (NCPC)",
            slug: "ncpc",
            type: "Centre",
            posts: [
                { bs: "05", postName: "Chowkidar / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "14", postName: "Social Welfare Assistant", qualification: "Bachelor’s in Social Work", ageLimit: "22–30" },
                { bs: "16", postName: "Child Protection Officer", qualification: "Master’s in Social Work / Psychology", ageLimit: "25–35" },
                { bs: "17", postName: "Assistant Director (Child Services)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + 5 yrs experience", ageLimit: "30–45" },
                { bs: "19", postName: "Director", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "20", postName: "Joint Secretary", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Directorate General of Special Education",
            slug: "dgse",
            type: "Directorate",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Special Education Teacher", qualification: "Bachelor’s in Education / Special Education", ageLimit: "22–30" },
                { bs: "16", postName: "Senior Instructor", qualification: "Master’s in Education / Special Education", ageLimit: "25–35" },
                { bs: "17", postName: "Assistant Director (Training)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Deputy Director", qualification: "Master’s + 5 yrs experience", ageLimit: "30–45" },
                { bs: "19", postName: "Director", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "20", postName: "Joint Secretary", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
    ],
};
