import type { Ministry } from "./types";

export const industriesProduction: Ministry = {
    name: "Ministry of Industries & Production",
    slug: "industries-production",
    departments: [
        {
            name: "Small and Medium Enterprises Development Authority (SMEDA)",
            slug: "smeda",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Business Development Officer", qualification: "Bachelor’s in Business Administration", ageLimit: "22–30" },
                { bs: "16", postName: "Research Associate", qualification: "Master’s in Economics / Business", ageLimit: "25–35" },
                { bs: "17", postName: "Assistant Manager", qualification: "Master’s + 2 yrs relevant experience", ageLimit: "28–35" },
                { bs: "18", postName: "Manager", qualification: "Master’s + 5 yrs experience", ageLimit: "30–45" },
                { bs: "19", postName: "Senior Manager", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "20", postName: "Joint Secretary (SMEDA)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Pakistan Industrial Development Corporation (PIDC)",
            slug: "pidc",
            type: "Corporation",
            posts: [
                { bs: "05", postName: "Peon / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "11", postName: "Accounts Assistant", qualification: "Intermediate; basic accounting", ageLimit: "18–30" },
                { bs: "14", postName: "Assistant Manager (Projects)", qualification: "Bachelor’s in Engineering / Business", ageLimit: "22–30" },
                { bs: "16", postName: "Manager (Projects)", qualification: "Master’s + 2 yrs experience", ageLimit: "25–35" },
                { bs: "17", postName: "Deputy Manager", qualification: "Master’s + 5 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Senior Manager / Director (Projects)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director", qualification: "Head of directorate", ageLimit: "35–55" },
                { bs: "20", postName: "Joint Secretary (PIDC)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Engineering Development Board (EDB)",
            slug: "edb",
            type: "Board",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Technical Officer", qualification: "Bachelor’s in Engineering", ageLimit: "22–30" },
                { bs: "16", postName: "Assistant Director (Engineering)", qualification: "Master’s in Engineering", ageLimit: "25–35" },
                { bs: "17", postName: "Deputy Director", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director General", qualification: "Head of board", ageLimit: "35–55" },
                { bs: "20", postName: "Joint Secretary (EDB)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "National Productivity Organization (NPO)",
            slug: "npo",
            type: "Organization",
            posts: [
                { bs: "05", postName: "Peon / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "14", postName: "Productivity Improvement Officer", qualification: "Bachelor’s in Engineering / Management", ageLimit: "22–30" },
                { bs: "16", postName: "Assistant Director (Productivity)", qualification: "Master’s in Management / Economics", ageLimit: "25–35" },
                { bs: "17", postName: "Deputy Director", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director General", qualification: "Head of organization", ageLimit: "35–55" },
                { bs: "20", postName: "Joint Secretary (NPO)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
    ],
};
