import type { Ministry } from "./types";

export const informationBroadcasting: Ministry = {
    name: "Ministry of Information & Broadcasting",
    slug: "information-broadcasting",
    departments: [
        {
            name: "Pakistan Television Corporation (PTV)",
            slug: "ptv",
            type: "Corporation",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Graphic Designer", qualification: "Bachelor’s in Graphic Design", ageLimit: "21–30" },
                { bs: "13", postName: "Video Editor", qualification: "Bachelor’s in Multimedia", ageLimit: "21–30" },
                { bs: "14", postName: "Broadcast Technician", qualification: "Diploma in Electronics / TV Production", ageLimit: "18–30" },
                { bs: "15", postName: "Assistant Producer", qualification: "Bachelor’s in Mass Communication", ageLimit: "21–35" },
                { bs: "16", postName: "Producer", qualification: "Master’s in Mass Communication", ageLimit: "25–35" },
                { bs: "17", postName: "Senior Producer", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "18", postName: "Deputy Director (Programming)", qualification: "Master’s + relevant experience", ageLimit: "30–45" },
                { bs: "19", postName: "Director (Engineering)", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "20", postName: "Managing Director", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Secretary (Information)", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Information & Broadcasting", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Pakistan Broadcasting Corporation (PBC)",
            slug: "pbc",
            type: "Corporation",
            posts: [
                { bs: "05", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver / Dispatch Rider", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Radio Operator", qualification: "Intermediate; radio operation certificate", ageLimit: "18–30" },
                { bs: "12", postName: "Sound Engineer", qualification: "Diploma in Audio Engineering", ageLimit: "21–30" },
                { bs: "13", postName: "Programme Assistant", qualification: "Bachelor’s in Media Studies", ageLimit: "21–30" },
                { bs: "14", postName: "Broadcast Announcer", qualification: "Bachelor’s; voice training", ageLimit: "21–35" },
                { bs: "15", postName: "Assistant Station Manager", qualification: "Master’s in Mass Communication", ageLimit: "25–35" },
                { bs: "16", postName: "Station Manager", qualification: "Master’s + experience", ageLimit: "28–40" },
                { bs: "17", postName: "Deputy Director (Broadcasting)", qualification: "Master’s + 2 yrs experience", ageLimit: "30–45" },
                { bs: "18", postName: "Director (Administration)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "19", postName: "Director General (PBC)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "20", postName: "Chairman Board of Management", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Information & Broadcasting", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Press Information Department (PID)",
            slug: "pid",
            type: "Department",
            posts: [
                { bs: "05", postName: "Naib Qasid / Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Photographer", qualification: "Diploma in Photography", ageLimit: "21–30" },
                { bs: "13", postName: "Public Relations Assistant", qualification: "Bachelor’s in Mass Communication", ageLimit: "21–35" },
                { bs: "14", postName: "Information Officer", qualification: "Master’s in Media Studies", ageLimit: "25–35" },
                { bs: "15", postName: "Assistant Director (Press Release)", qualification: "Master’s + experience", ageLimit: "28–40" },
                { bs: "16", postName: "Deputy Director (PR)", qualification: "Master’s + 2 yrs experience", ageLimit: "30–45" },
                { bs: "17", postName: "Director (Communications)", qualification: "Senior service grade", ageLimit: "35–50" },
                { bs: "18", postName: "Additional Director General", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "19", postName: "Director General (PID)", qualification: "Head of Department", ageLimit: "45–65" },
                { bs: "20", postName: "Joint Secretary (Information)", qualification: "Head of cadre", ageLimit: "50–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Information & Broadcasting", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
    ],
};