import type { Ministry } from "./types";

export const kashmirGb: Ministry = {
    name: "Ministry of Kashmir Affairs & Gilgit-Baltistan",
    slug: "kashmir-gb",
    departments: [
        {
            name: "Kashmir Cell",
            slug: "kashmir-cell",
            type: "Cell",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Research Assistant", qualification: "Bachelor’s in Social Sciences / International Relations", ageLimit: "22–30" },
                { bs: "13", postName: "Data Entry Operator", qualification: "Intermediate; 40 wpm typing", ageLimit: "18–30" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "15", postName: "Assistant Protocol Officer", qualification: "Bachelor’s in Public Administration", ageLimit: "22–35" },
                { bs: "16", postName: "Protocol Officer", qualification: "Master’s in International Relations", ageLimit: "25–35" },
                { bs: "17", postName: "Section Officer", qualification: "Master’s + 2 yrs relevant experience", ageLimit: "28–40" },
                { bs: "18", postName: "Deputy Director (Kashmir Affairs)", qualification: "Master’s + senior service", ageLimit: "30–50" },
                { bs: "19", postName: "Director (Kashmir Affairs)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "20", postName: "Joint Secretary (Kashmir Affairs)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Kashmir Affairs & GB", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Gilgit-Baltistan Secretariat",
            slug: "gb-secretariat",
            type: "Secretariat",
            posts: [
                { bs: "05", postName: "Chowkidar / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Computer Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Translator", qualification: "Bachelor’s in English/Urdu", ageLimit: "22–35" },
                { bs: "13", postName: "Research Officer", qualification: "Master’s in Public Policy", ageLimit: "25–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "15", postName: "Assistant Director (GB Affairs)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–40" },
                { bs: "16", postName: "Deputy Secretary (GB Secretariat)", qualification: "Master’s degree", ageLimit: "30–45" },
                { bs: "17", postName: "Director (GB Secretariat)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "18", postName: "Additional Secretary (GB)", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "19", postName: "Joint Secretary (GB Affairs)", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "20", postName: "Additional Federal Secretary", qualification: "Head of cadre", ageLimit: "50–65" },
                { bs: "21", postName: "Federal Secretary", qualification: "Head of service", ageLimit: "55–65" },
                { bs: "22", postName: "Chief Secretary GB", qualification: "Head of GB Secretariat", ageLimit: "55–65" },
            ],
        },
        {
            name: "AJK Council",
            slug: "ajk-council",
            type: "Council",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Legislative Assistant", qualification: "Bachelor’s in Law/Political Science", ageLimit: "22–35" },
                { bs: "13", postName: "Committee Coordinator", qualification: "Bachelor’s/Master’s in Public Administration", ageLimit: "25–35" },
                { bs: "14", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "15", postName: "Secretary to Council", qualification: "Bachelor’s degree", ageLimit: "25–40" },
                { bs: "16", postName: "Deputy Secretary", qualification: "Master’s degree", ageLimit: "30–45" },
                { bs: "17", postName: "Director (Legislative)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "18", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–60" },
                { bs: "19", postName: "Joint Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "20", postName: "Federal Secretary (AJK Affairs)", qualification: "Federal Secretariat grade", ageLimit: "50–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "55–65" },
                { bs: "22", postName: "Federal Secretary, Kashmir Affairs & GB", qualification: "Head of service", ageLimit: "60–65" },
            ],
        },
    ],
};