import type { Ministry } from "./types";

export const lawJustice: Ministry = {
    name: "Ministry of Law & Justice",
    slug: "law-justice",
    departments: [
        {
            name: "Attorney General's Office",
            slug: "attorney-general",
            type: "Office",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Legal Assistant", qualification: "LLB / LLM candidate", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Bachelor’s in Law / Social Sciences", ageLimit: "22–35" },
                { bs: "15", postName: "Personal Assistant", qualification: "Bachelor’s degree", ageLimit: "22–35" },
                { bs: "16", postName: "Assistant Law Officer", qualification: "LLB", ageLimit: "25–35" },
                { bs: "17", postName: "Law Officer", qualification: "LLB + practice experience", ageLimit: "25–40" },
                { bs: "18", postName: "Deputy Attorney General", qualification: "Senior Advocate", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Attorney General", qualification: "Senior bar member", ageLimit: "35–55" },
                { bs: "20", postName: "Attorney General of Pakistan", qualification: "Chief law officer of the state", ageLimit: "40–65" },
            ],
        },
        {
            name: "Pakistan Law and Justice Commission",
            slug: "law-justice-commission",
            type: "Commission",
            posts: [
                { bs: "05", postName: "Peon / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Research Analyst", qualification: "Bachelor’s/Master’s in Law / Public Policy", ageLimit: "22–35" },
                { bs: "13", postName: "Assistant Director (Research)", qualification: "Master’s in Law / Social Sciences", ageLimit: "25–40" },
                { bs: "14", postName: "Director (Research)", qualification: "Senior service grade", ageLimit: "30–55" },
                { bs: "15", postName: "Deputy Secretary", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "16", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "17", postName: "Federal Secretary (Law & Justice)", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Council of Islamic Ideology",
            slug: "council-islamic-ideology",
            type: "Council",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Research Assistant", qualification: "Bachelor’s in Islamic Studies / Law", ageLimit: "22–35" },
                { bs: "13", postName: "Senior Research Assistant", qualification: "Master’s in Islamic Studies / Law", ageLimit: "25–40" },
                { bs: "14", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–55" },
                { bs: "15", postName: "Director", qualification: "Head of department", ageLimit: "35–60" },
                { bs: "16", postName: "Additional Secretary", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "17", postName: "Federal Secretary (CII)", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Federal Shariat Court",
            slug: "federal-shariat-court",
            type: "Court",
            posts: [
                { bs: "05", postName: "Chowkidar / Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Research Assistant", qualification: "Bachelor’s in Law / Islamic Studies", ageLimit: "22–35" },
                { bs: "14", postName: "Joint Sharia Judge", qualification: "LLB + Sharia specialization", ageLimit: "30–50" },
                { bs: "15", postName: "Judge", qualification: "Senior Advocate + judicial experience", ageLimit: "35–60" },
                { bs: "16", postName: "Chief Justice", qualification: "Head of Federal Shariat Court", ageLimit: "50–65" },
            ],
        },
    ],
};