import type { Ministry } from "./types";

export const maritimeAffairs: Ministry = {
    name: "Ministry of Maritime Affairs",
    slug: "maritime-affairs",
    departments: [
        {
            name: "Karachi Port Trust (KPT)",
            slug: "kpt",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Port Health Officer", qualification: "B.Sc in Microbiology / Public Health", ageLimit: "22–35" },
                { bs: "13", postName: "Traffic Supervisor", qualification: "Bachelor’s in Business Administration", ageLimit: "22–35" },
                { bs: "14", postName: "Marine Engineering Assistant", qualification: "Diploma in Marine Engineering", ageLimit: "18–30" },
                { bs: "15", postName: "Harbour Master Assistant", qualification: "Bachelor’s in Maritime Studies", ageLimit: "22–35" },
                { bs: "16", postName: "Harbour Master", qualification: "Master’s in Maritime Affairs", ageLimit: "25–40" },
                { bs: "17", postName: "Deputy Director (Operations)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "18", postName: "Director (Port Operations)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director General", qualification: "Head of Authority cadre", ageLimit: "35–55" },
                { bs: "20", postName: "Member Board of Trustees", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Chairman Board of Trustees", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Maritime Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Port Qasim Authority (PQA)",
            slug: "pqa",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Chowkidar / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Customs Inspector Assistant", qualification: "Matric; relevant training", ageLimit: "18–30" },
                { bs: "13", postName: "Traffic Control Officer", qualification: "Bachelor’s in Logistics", ageLimit: "22–35" },
                { bs: "14", postName: "Marine Survey Officer", qualification: "Diploma in Shipping Technology", ageLimit: "18–30" },
                { bs: "15", postName: "Assistant Harbour Master", qualification: "Bachelor’s in Maritime Studies", ageLimit: "22–35" },
                { bs: "16", postName: "Harbour Master", qualification: "Master’s in Maritime Affairs", ageLimit: "25–40" },
                { bs: "17", postName: "Deputy Director (Logistics)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "18", postName: "Director (Port Administration)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "35–55" },
                { bs: "20", postName: "Member Board", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Chairman Board", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Maritime Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Gwadar Port Authority (GPA)",
            slug: "gpa",
            type: "Authority",
            posts: [
                { bs: "05", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Radio Operator", qualification: "Intermediate; radio operation certificate", ageLimit: "18–30" },
                { bs: "12", postName: "Security Officer Assistant", qualification: "Matric; relevant training", ageLimit: "18–30" },
                { bs: "13", postName: "Port Operations Officer", qualification: "Bachelor’s in Logistics", ageLimit: "22–35" },
                { bs: "14", postName: "Marine Pilot", qualification: "Diploma in Marine Navigation", ageLimit: "18–35" },
                { bs: "15", postName: "Assistant Harbour Master", qualification: "Bachelor’s in Maritime Studies", ageLimit: "22–35" },
                { bs: "16", postName: "Harbour Master", qualification: "Master’s in Maritime Affairs", ageLimit: "25–40" },
                { bs: "17", postName: "Deputy Director (Security)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "18", postName: "Director (Operations)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "35–55" },
                { bs: "20", postName: "Member Board", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Chairman Board", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Maritime Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Pakistan Marine Academy",
            slug: "pakistan-marine-academy",
            type: "Academy",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Computer Lab Assistant", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Lab Technician", qualification: "Diploma in Marine Lab Technology", ageLimit: "18–30" },
                { bs: "13", postName: "Instructor Assistant", qualification: "Bachelor’s in Maritime Studies", ageLimit: "22–35" },
                { bs: "14", postName: "Lecturer", qualification: "Master’s in Maritime Studies / Engineering", ageLimit: "25–40" },
                { bs: "15", postName: "Senior Lecturer", qualification: "Master’s + teaching experience", ageLimit: "28–45" },
                { bs: "16", postName: "Assistant Professor", qualification: "PhD/ MPhil in relevant field", ageLimit: "30–50" },
                { bs: "17", postName: "Associate Professor", qualification: "PhD + experience", ageLimit: "35–60" },
                { bs: "18", postName: "Professor", qualification: "PhD + senior experience", ageLimit: "40–65" },
                { bs: "19", postName: "Dean of Studies", qualification: "Professor grade", ageLimit: "45–65" },
                { bs: "20", postName: "Director (Academics)", qualification: "Senior academic service", ageLimit: "45–65" },
                { bs: "21", postName: "Commandant", qualification: "Head of Academy", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Maritime Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
    ],
};
