import type { Ministry } from "./types";

export const narcoticsControl: Ministry = {
    name: "Ministry of Narcotics Control",
    slug: "narcotics-control",
    departments: [
        {
            name: "Anti-Narcotics Force (ANF)",
            slug: "anf",
            type: "Force",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Constable", qualification: "Matric; physical standards", ageLimit: "18–25" },
                { bs: "14", postName: "Assistant Sub-Inspector (ASI)", qualification: "Intermediate", ageLimit: "18–25" },
                { bs: "15", postName: "Sub-Inspector (SI)", qualification: "Bachelor’s degree", ageLimit: "18–28" },
                { bs: "16", postName: "Inspector", qualification: "Bachelor’s degree + training", ageLimit: "20–30" },
                { bs: "17", postName: "Assistant Superintendent", qualification: "Master’s degree", ageLimit: "22–32" },
                { bs: "18", postName: "Superintendent", qualification: "Master’s + 3 yrs experience", ageLimit: "25–35" },
                { bs: "19", postName: "Deputy Director (Operations)", qualification: "Master’s + senior service", ageLimit: "28–40" },
                { bs: "20", postName: "Director (ANF)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "21", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "35–60" },
                { bs: "22", postName: "Director General ANF", qualification: "Head of Force", ageLimit: "40–65" },
            ],
        },
        {
            name: "Regional Directorates of ANF",
            slug: "anf-regional",
            type: "Directorate",
            posts: [
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "13", postName: "Regional Inspector", qualification: "Bachelor’s degree + experience", ageLimit: "22–35" },
                { bs: "15", postName: "Deputy Regional Director", qualification: "Master’s degree", ageLimit: "25–40" },
                { bs: "17", postName: "Regional Director (ANF)", qualification: "Senior service grade", ageLimit: "28–50" },
                { bs: "19", postName: "Additional Director General (Regional)", qualification: "Head of cadre", ageLimit: "35–60" },
                { bs: "21", postName: "Director General (Regional)", qualification: "Head of service", ageLimit: "40–65" },
            ],
        },
        {
            name: "Policy & Coordination Wing",
            slug: "policy-coordination-wing",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Secretariat Assistant", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "13", postName: "Research Analyst", qualification: "Master’s in Public Policy", ageLimit: "22–35" },
                { bs: "15", postName: "Deputy Director (Policy)", qualification: "Master’s + 2 yrs experience", ageLimit: "25–40" },
                { bs: "17", postName: "Director (Policy)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Additional Secretary (Narcotics)", qualification: "Head of cadre", ageLimit: "35–60" },
                { bs: "22", postName: "Federal Secretary, Narcotics Control", qualification: "Head of service", ageLimit: "40–65" },
            ],
        },
    ],
};
