import type { Ministry } from "./types";

export const overseasHrd: Ministry = {
    name: "Ministry of Overseas Pakistanis & Human Resource Development",
    slug: "overseas-hrd",
    departments: [
        {
            name: "Overseas Employment Corporation (OEC)",
            slug: "oec",
            type: "Corporation",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Assistant Employment Officer", qualification: "Bachelor’s in Sociology/Business Administration", ageLimit: "22–35" },
                { bs: "13", postName: "Research Assistant", qualification: "Bachelor’s/Master’s in Economics", ageLimit: "22–35" },
                { bs: "14", postName: "Assistant Director (Recruitment)", qualification: "Master’s in Public Administration", ageLimit: "25–40" },
                { bs: "15", postName: "Deputy Director (Placement)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "16", postName: "Director (OEC)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "17", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "35–60" },
                { bs: "20", postName: "Chairman, OEC Board", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "22", postName: "Federal Secretary, Overseas Pakistanis & HRD", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Bureau of Emigration & Overseas Employment",
            slug: "beoe",
            type: "Bureau",
            posts: [
                { bs: "05", postName: "Chowkidar / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Emigration Officer", qualification: "Bachelor’s in Sociology/Law", ageLimit: "22–35" },
                { bs: "13", postName: "Senior Emigration Officer", qualification: "Master’s + 2 yrs experience", ageLimit: "25–40" },
                { bs: "14", postName: "Assistant Director (Emigration)", qualification: "Master’s in Public Policy", ageLimit: "28–45" },
                { bs: "16", postName: "Director (BeOE)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "18", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "35–60" },
                { bs: "22", postName: "Federal Secretary, Overseas Pakistanis & HRD", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Employees' Old-Age Benefits Institution (EOBI)",
            slug: "eobi",
            type: "Institution",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Accounts Assistant", qualification: "Intermediate; basic accounting", ageLimit: "18–30" },
                { bs: "12", postName: "Claims Processing Officer", qualification: "Bachelor’s in Commerce/Finance", ageLimit: "22–35" },
                { bs: "14", postName: "Superintendent", qualification: "Bachelor’s + 2 yrs experience", ageLimit: "25–45" },
                { bs: "16", postName: "Assistant Director (Benefits)", qualification: "Master’s in Public Admin/Finance", ageLimit: "28–50" },
                { bs: "18", postName: "Director (EOBI)", qualification: "Senior service grade", ageLimit: "30–55" },
                { bs: "20", postName: "Chairman EOBI Board", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "22", postName: "Federal Secretary, Overseas Pakistanis & HRD", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Workers Welfare Fund (WWF)",
            slug: "wwf",
            type: "Fund",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Fund Analyst", qualification: "Bachelor’s in Finance/Economics", ageLimit: "22–35" },
                { bs: "14", postName: "Superintendent", qualification: "Bachelor’s + 2 yrs experience", ageLimit: "25–45" },
                { bs: "16", postName: "Assistant Director (Fund Management)", qualification: "Master’s in Finance", ageLimit: "28–50" },
                { bs: "18", postName: "Director (WWF)", qualification: "Senior service grade", ageLimit: "30–55" },
                { bs: "20", postName: "Chairman, WWF Board", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "22", postName: "Federal Secretary, Overseas Pakistanis & HRD", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
    ],
};