import type { Ministry } from "./types";

export const parliamentaryAffairs: Ministry = {
    name: "Ministry of Parliamentary Affairs",
    slug: "parliamentary-affairs",
    departments: [
        {
            name: "National Assembly Secretariat Liaison Wing",
            slug: "na-liaison-wing",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic IT skills", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Committee Assistant", qualification: "Bachelor’s in Political Science / Public Admin", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s in Political Science", ageLimit: "25–40" },
                { bs: "15", postName: "Protocol Officer", qualification: "Bachelor’s in International Relations", ageLimit: "22–35" },
                { bs: "16", postName: "Section Officer", qualification: "Master’s in Public Policy", ageLimit: "25–40" },
                { bs: "17", postName: "Deputy Director (Liaison)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "18", postName: "Director (Liaison)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "19", postName: "Joint Secretary (NA Liaison)", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "20", postName: "Additional Secretary (Parliamentary Affairs)", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "21", postName: "Secretary (Parliamentary Affairs)", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Parliamentary Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Senate Coordination Wing",
            slug: "senate-coordination",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Peon / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Committee Assistant", qualification: "Bachelor’s in Political Science / Public Admin", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s in Political Science", ageLimit: "25–40" },
                { bs: "15", postName: "Section Officer", qualification: "Master’s in Public Policy", ageLimit: "25–40" },
                { bs: "16", postName: "Deputy Director (Coordination)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "17", postName: "Director (Coordination)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "18", postName: "Joint Secretary (Senate Coordination)", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "19", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "20", postName: "Secretary (Parliamentary Affairs)", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "21", postName: "Federal Secretary, Parliamentary Affairs", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Parliamentary Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Parliamentary Business Section",
            slug: "parliamentary-business",
            type: "Section",
            posts: [
                { bs: "05", postName: "Chowkidar / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Business Assistant", qualification: "Bachelor’s in Public Admin/Political Science", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s in Political Science", ageLimit: "25–40" },
                { bs: "15", postName: "Section Officer", qualification: "Master’s in Public Policy", ageLimit: "25–40" },
                { bs: "16", postName: "Deputy Director (Business)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "17", postName: "Director (Business)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "18", postName: "Joint Secretary (Parliamentary Business)", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "19", postName: "Additional Secretary", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "20", postName: "Secretary (Parliamentary Affairs)", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "21", postName: "Federal Secretary, Parliamentary Affairs", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Parliamentary Affairs", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
    ],
};