import type { Ministry } from "./types";

export const planningDevelopment: Ministry = {
    name: "Ministry of Planning, Development & Special Initiatives",
    slug: "planning-development",
    departments: [
        {
            name: "Pakistan Bureau of Statistics (PBS)",
            slug: "pbs",
            type: "Bureau",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "07", postName: "Survey Assistant", qualification: "Intermediate; basic statistics", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Statistician Assistant", qualification: "Bachelor’s in Statistics/Maths", ageLimit: "21–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Technical Officer", qualification: "Diploma in Statistics/CS", ageLimit: "21–30" },
                { bs: "13", postName: "Superintendent", qualification: "Bachelor’s degree", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s in Statistics/Economics", ageLimit: "25–40" },
                { bs: "15", postName: "Assistant Director (Statistics)", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "16", postName: "Deputy Director (Data)", qualification: "Master’s + 2 yrs experience", ageLimit: "30–50" },
                { bs: "17", postName: "Director (Survey)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "18", postName: "Additional Director General", qualification: "Head of bureau cadre", ageLimit: "40–60" },
                { bs: "19", postName: "Member PBS Board", qualification: "Federal Secretariat grade", ageLimit: "45–65" },
                { bs: "20", postName: "Chairman PBS Board", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "21", postName: "Federal Secretary, Planning & Dev", qualification: "Head of service", ageLimit: "55–65" },
                { bs: "22", postName: "Chief Planning Commissioner", qualification: "Head of commission", ageLimit: "55–65" },
            ],
        },
        {
            name: "Planning Commission of Pakistan",
            slug: "planning-commission",
            type: "Commission",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Stenotypist", qualification: "Intermediate + shorthand", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Research Assistant", qualification: "Bachelor’s in Economics/Planning", ageLimit: "21–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Programme Officer", qualification: "Bachelor’s in Public Policy", ageLimit: "22–35" },
                { bs: "13", postName: "Assistant Director (Planning)", qualification: "Master’s in Planning/Economics", ageLimit: "25–40" },
                { bs: "14", postName: "Deputy Director", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "15", postName: "Director (Special Initiatives)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Additional Secretary", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "17", postName: "Federal Secretary (Planning)", qualification: "Head of service", ageLimit: "45–65" },
                { bs: "18", postName: "Planning Commissioner", qualification: "Head of commission", ageLimit: "50–65" },
            ],
        },
        {
            name: "Public Sector Development Programme (PSDP)",
            slug: "psdp",
            type: "Programme",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand", ageLimit: "18–30" },
                { bs: "10", postName: "Project Assistant", qualification: "Bachelor’s in Public Admin/Engineering", ageLimit: "22–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Budget Officer", qualification: "Master’s in Finance", ageLimit: "25–40" },
                { bs: "13", postName: "Assistant Director (Projects)", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "14", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "15", postName: "Director (PSDP)", qualification: "Head of programme", ageLimit: "35–60" },
            ],
        },
        {
            name: "Centre for Rural Economy",
            slug: "rural-economy-centre",
            type: "Centre",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Field Assistant", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Research Assistant", qualification: "Bachelor’s in Agriculture/Economics", ageLimit: "22–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Programme Officer", qualification: "Master’s in Rural Development", ageLimit: "25–40" },
                { bs: "13", postName: "Assistant Director (Rural Dev)", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "14", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "15", postName: "Director (Centre)", qualification: "Head of centre", ageLimit: "35–60" },
            ],
        },
    ],
};