import type { Ministry } from "./types";

export const privatisation: Ministry = {
    name: "Ministry of Privatisation",
    slug: "privatisation",
    departments: [
        {
            name: "Privatisation Commission",
            slug: "privatisation-commission",
            type: "Commission",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Research Assistant", qualification: "Bachelor’s in Economics/Business Administration", ageLimit: "22–35" },
                { bs: "14", postName: "Audit Officer", qualification: "Bachelor’s in Finance/Commerce", ageLimit: "22–35" },
                { bs: "15", postName: "Assistant Director (Privatisation Planning)", qualification: "Master’s in Public Policy/Economics", ageLimit: "25–40" },
                { bs: "16", postName: "Deputy Director", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "17", postName: "Director (Commission)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "18", postName: "Additional Secretary (Privatisation)", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "19", postName: "Joint Secretary", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "20", postName: "Member Board", qualification: "Head of board cadre", ageLimit: "45–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Privatisation", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
        {
            name: "Transaction Wing",
            slug: "transaction-wing",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Peon / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm", ageLimit: "18–30" },
                { bs: "13", postName: "Transaction Officer", qualification: "Bachelor’s in Finance/Economics", ageLimit: "22–35" },
                { bs: "14", postName: "Legal Assistant", qualification: "LLB candidate", ageLimit: "22–35" },
                { bs: "15", postName: "Assistant Director (Transactions)", qualification: "Master’s in Business Administration/Economics", ageLimit: "25–40" },
                { bs: "16", postName: "Deputy Director (Transactions)", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "17", postName: "Director (Transactions)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "18", postName: "Additional Secretary (Transactions)", qualification: "Federal Secretariat grade", ageLimit: "35–60" },
                { bs: "19", postName: "Joint Secretary", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "20", postName: "Member Board", qualification: "Head of board cadre", ageLimit: "45–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Privatisation", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
        {
            name: "Legal & Litigation Wing",
            slug: "legal-litigation",
            type: "Wing",
            posts: [
                { bs: "05", postName: "Chowkidar / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm", ageLimit: "18–30" },
                { bs: "12", postName: "Legal Assistant", qualification: "LLB candidate", ageLimit: "22–35" },
                { bs: "13", postName: "Junior Legal Officer", qualification: "LLB", ageLimit: "22–40" },
                { bs: "14", postName: "Senior Legal Officer", qualification: "LLB + 5 yrs experience", ageLimit: "28–50" },
                { bs: "15", postName: "Assistant Director (Legal)", qualification: "LLB + 2 yrs experience", ageLimit: "25–45" },
                { bs: "16", postName: "Deputy Director (Legal)", qualification: "LLM / LLB + experience", ageLimit: "28–50" },
                { bs: "17", postName: "Director (Legal)", qualification: "Senior Advocate grade", ageLimit: "35–60" },
                { bs: "18", postName: "Additional Secretary (Legal)", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "19", postName: "Joint Secretary", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "20", postName: "Member Board", qualification: "Head of board cadre", ageLimit: "50–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "55–65" },
                { bs: "22", postName: "Federal Secretary, Privatisation", qualification: "Head of service", ageLimit: "60–65" },
            ],
        },
    ],
};