import type { Ministry } from "./types";

export const railways: Ministry = {
    name: "Ministry of Railways",
    slug: "railways",
    departments: [
        {
            name: "Pakistan Railways Headquarters",
            slug: "railways-hq",
            type: "Department",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Dispatch Rider", qualification: "Primary pass; motorbike licence", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Ticket Examiner", qualification: "Matric", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Accountant", qualification: "Bachelor’s in Commerce", ageLimit: "21–35" },
                { bs: "13", postName: "Station Master Assistant", qualification: "Bachelor’s degree", ageLimit: "22–35" },
                { bs: "14", postName: "Station Master", qualification: "Bachelor’s + training", ageLimit: "25–40" },
                { bs: "15", postName: "Assistant Bridge Engineer", qualification: "Diploma in Civil Engineering", ageLimit: "22–35" },
                { bs: "16", postName: "Bridge Engineer", qualification: "B.Sc in Civil Engineering", ageLimit: "25–40" },
                { bs: "17", postName: "Senior Signal Engineer", qualification: "B.Sc in Electrical/Electronics", ageLimit: "28–45" },
                { bs: "18", postName: "Deputy Director (Operations)", qualification: "Master’s degree", ageLimit: "30–50" },
                { bs: "19", postName: "Director (Railway Operations)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "20", postName: "Member Railways Board", qualification: "Federal Secretariat grade", ageLimit: "40–60" },
                { bs: "21", postName: "Additional Member Railways Board", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "22", postName: "Federal Secretary, Railways", qualification: "Head of service", ageLimit: "50–65" },
            ],
        },
        {
            name: "Pakistan Railway Police",
            slug: "railway-police",
            type: "Force",
            posts: [
                { bs: "05", postName: "Constable", qualification: "Matric; police training", ageLimit: "18–25" },
                { bs: "07", postName: "Head Constable", qualification: "Intermediate; police training", ageLimit: "18–30" },
                { bs: "09", postName: "Lance Naik", qualification: "Intermediate", ageLimit: "18–30" },
                { bs: "11", postName: "Naik", qualification: "Intermediate", ageLimit: "18–30" },
                { bs: "14", postName: "Assistant Sub-Inspector (ASI)", qualification: "Intermediate; police training", ageLimit: "18–30" },
                { bs: "15", postName: "Sub-Inspector (SI)", qualification: "Bachelor’s degree", ageLimit: "18–28" },
                { bs: "16", postName: "Inspector", qualification: "Bachelor’s + training", ageLimit: "20–30" },
                { bs: "17", postName: "Assistant Superintendent of Police", qualification: "Master’s degree", ageLimit: "22–32" },
                { bs: "18", postName: "Superintendent of Police", qualification: "Master’s + experience", ageLimit: "25–40" },
                { bs: "19", postName: "Deputy Inspector General", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "20", postName: "Inspector General (Railway Police)", qualification: "Head of force", ageLimit: "35–60" },
                { bs: "21", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "22", postName: "Director General, Railway Police", qualification: "Head of service", ageLimit: "45–65" },
            ],
        },
        {
            name: "Pakistan Railways Academy Walton",
            slug: "railways-academy",
            type: "Academy",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Lab Assistant", qualification: "Intermediate; technical training", ageLimit: "18–30" },
                { bs: "12", postName: "Instructor Assistant", qualification: "Diploma in Engineering", ageLimit: "22–35" },
                { bs: "13", postName: "Instructor", qualification: "Bachelor’s in Engineering/Transport", ageLimit: "25–40" },
                { bs: "14", postName: "Senior Instructor", qualification: "Master’s in Education/Engineering", ageLimit: "28–45" },
                { bs: "15", postName: "Assistant Director (Training)", qualification: "Master’s + teaching experience", ageLimit: "30–50" },
                { bs: "16", postName: "Deputy Director (Academics)", qualification: "Senior academic service", ageLimit: "35–60" },
                { bs: "17", postName: "Director (Academics)", qualification: "Head of academy cadre", ageLimit: "40–65" },
                { bs: "18", postName: "Additional Director General", qualification: "Head of cadre", ageLimit: "45–65" },
                { bs: "19", postName: "Commandant, RSA Walton", qualification: "Head of academy", ageLimit: "50–65" },
                { bs: "20", postName: "Principal Officers Board Member", qualification: "Federal Secretariat grade", ageLimit: "55–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "60–65" },
                { bs: "22", postName: "Federal Secretary, Railways", qualification: "Head of service", ageLimit: "65–70" },
            ],
        },
        {
            name: "Railway Construction Pakistan Limited (RAILCOP)",
            slug: "railcop",
            type: "Corporation",
            posts: [
                { bs: "05", postName: "Peon / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Surveyor", qualification: "Diploma in Civil Engineering", ageLimit: "22–35" },
                { bs: "13", postName: "Draftsman", qualification: "Diploma in Civil Draftsmanship", ageLimit: "22–35" },
                { bs: "14", postName: "Sub-Engineer (Civil)", qualification: "Diploma in Civil Engineering", ageLimit: "22–35" },
                { bs: "15", postName: "Assistant Engineer", qualification: "B.Sc in Civil Engineering", ageLimit: "25–40" },
                { bs: "16", postName: "Executive Engineer", qualification: "B.Sc + 5 yrs experience", ageLimit: "28–45" },
                { bs: "17", postName: "Superintending Engineer", qualification: "Senior Civil Engineer", ageLimit: "30–50" },
                { bs: "18", postName: "Additional Director General", qualification: "Head of corporation cadre", ageLimit: "35–60" },
                { bs: "19", postName: "Director General (RAILCOP)", qualification: "Head of corporation", ageLimit: "40–65" },
                { bs: "20", postName: "Member Board", qualification: "Federal Secretariat grade", ageLimit: "45–65" },
                { bs: "21", postName: "Additional Federal Secretary", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "22", postName: "Federal Secretary, Railways", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
    ],
};