import type { Ministry } from "./types";

export const scienceTech: Ministry = {
    name: "Ministry of Science & Technology",
    slug: "science-tech",
    departments: [
        {
            name: "Pakistan Council of Scientific & Industrial Research (PCSIR)",
            slug: "pcsir",
            type: "Council",
            posts: [
                { bs: "05", postName: "Naib Qasid / Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; basic computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Laboratory Technician", qualification: "Diploma in relevant field", ageLimit: "18–30" },
                { bs: "13", postName: "Scientific Assistant", qualification: "Bachelor’s in Science/Engineering", ageLimit: "22–35" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s in Science/Engineering", ageLimit: "25–40" },
                { bs: "15", postName: "Assistant Director (Research)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "16", postName: "Deputy Director (Labs)", qualification: "Master’s + 5 yrs experience", ageLimit: "30–50" },
                { bs: "17", postName: "Director (Research)", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "18", postName: "Additional Director General", qualification: "Head of council cadre", ageLimit: "40–60" },
                { bs: "19", postName: "Member Council", qualification: "Federal Secretariat grade", ageLimit: "45–65" },
                { bs: "20", postName: "Chairman Council", qualification: "Head of service", ageLimit: "50–65" },
                { bs: "21", postName: "Federal Secretary (Science & Tech)", qualification: "Head of service", ageLimit: "55–65" },
                { bs: "22", postName: "Minister of State (Science & Tech)", qualification: "Elected official", ageLimit: "30–65" },
            ],
        },
        {
            name: "Pakistan Science Foundation (PSF)",
            slug: "psf",
            type: "Foundation",
            posts: [
                { bs: "05", postName: "Peon / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Data Entry Operator", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Science Officer", qualification: "Bachelor’s in Science", ageLimit: "22–35" },
                { bs: "13", postName: "Programme Officer", qualification: "Master’s in Science/Public Policy", ageLimit: "25–40" },
                { bs: "14", postName: "Assistant Director (Programs)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "15", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Director (Foundation)", qualification: "Head of foundation cadre", ageLimit: "35–60" },
                { bs: "17", postName: "Additional Secretary / Member Board", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "22", postName: "Federal Secretary (Science & Tech)", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
        {
            name: "National Institute of Electronics (NIE)",
            slug: "nie",
            type: "Institute",
            posts: [
                { bs: "05", postName: "Naib Qasid / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Lab Assistant", qualification: "Intermediate; technical training", ageLimit: "18–30" },
                { bs: "12", postName: "Electronics Technician", qualification: "Diploma in Electronics", ageLimit: "18–30" },
                { bs: "13", postName: "Research Engineer", qualification: "Bachelor’s in Electronics/Telecom", ageLimit: "22–35" },
                { bs: "14", postName: "Assistant Director (Electronics)", qualification: "Master’s in Electronics", ageLimit: "25–45" },
                { bs: "15", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Director (Institute)", qualification: "Head of institute cadre", ageLimit: "35–60" },
                { bs: "21", postName: "Federal Secretary (Science & Tech)", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
        {
            name: "National Institute of Oceanography (NIO)",
            slug: "nio",
            type: "Institute",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "07", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "UDC / Lab Assistant", qualification: "Intermediate; lab training", ageLimit: "18–30" },
                { bs: "12", postName: "Oceanographic Technician", qualification: "Diploma in Marine Sciences", ageLimit: "18–30" },
                { bs: "13", postName: "Scientific Officer", qualification: "Bachelor’s in Marine / Environmental Sciences", ageLimit: "22–35" },
                { bs: "14", postName: "Assistant Director (Research)", qualification: "Master’s in Marine Science", ageLimit: "25–45" },
                { bs: "15", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Director (Oceanography)", qualification: "Head of institute cadre", ageLimit: "35–60" },
                { bs: "21", postName: "Federal Secretary (Science & Tech)", qualification: "Head of service", ageLimit: "55–65" },
            ],
        },
    ],
};