import type { Ministry } from "./types";

export const statesFrontierRegions: Ministry = {
    name: "Ministry of States & Frontier Regions",
    slug: "safar",
    departments: [
        {
            name: "Commissionerate for Afghan Refugees",
            slug: "afghan-refugees",
            type: "Commissionerate",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "07", postName: "Data Entry Operator", qualification: "Intermediate; typing 30 wpm", ageLimit: "18–30" },
                { bs: "08", postName: "Tracer", qualification: "Intermediate; geography/data skills", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Social Welfare Assistant", qualification: "Bachelor’s in Social Work", ageLimit: "21–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Field Officer", qualification: "Bachelor’s in Sociology/Anthropology", ageLimit: "22–35" },
                { bs: "13", postName: "Assistant Director (Field)", qualification: "Master’s in Social Sciences", ageLimit: "25–40" },
                { bs: "14", postName: "Senior Field Coordinator", qualification: "Master’s + experience", ageLimit: "28–45" },
                { bs: "15", postName: "Deputy Commissioner (Refugees)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Regional Director", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "17", postName: "Additional Director General", qualification: "Head of directorate cadre", ageLimit: "40–60" },
                { bs: "18", postName: "Director General (Refugees)", qualification: "Head of directorate", ageLimit: "45–65" },
                { bs: "19", postName: "Member Commissionerate Board", qualification: "Federal Secretariat grade", ageLimit: "50–70" },
                { bs: "20", postName: "Chairman Commissionerate Board", qualification: "Head of service", ageLimit: "55–70" },
                { bs: "21", postName: "Additional Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "58–70" },
                { bs: "22", postName: "Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "60–70" },
            ],
        },
        {
            name: "Frontier Regions Administration",
            slug: "fr-admin",
            type: "Administration",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Dispatch Rider", qualification: "Primary pass; motorcycle licence", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Administrative Officer Assistant", qualification: "Bachelor’s in Public Admin", ageLimit: "22–35" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Assistant Commissioner (FR)", qualification: "Master’s in Public Admin", ageLimit: "25–40" },
                { bs: "13", postName: "Deputy Commissioner (FR)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "14", postName: "Regional Commissioner", qualification: "Senior service grade", ageLimit: "35–55" },
                { bs: "15", postName: "Additional Secretary (FR)", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "16", postName: "Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "45–70" },
                { bs: "17", postName: "Chairman FR Administration Board", qualification: "Head of service", ageLimit: "50–70" },
                { bs: "18", postName: "Member Board (FR)", qualification: "Federal Secretariat grade", ageLimit: "55–70" },
                { bs: "19", postName: "Additional Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "58–70" },
                { bs: "20", postName: "Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "60–70" },
                { bs: "21", postName: "Chief Commissioner FR", qualification: "Head of administration", ageLimit: "60–70" },
                { bs: "22", postName: "Chief Secretary SAFR", qualification: "Head of SAFR ministry", ageLimit: "60–70" },
            ],
        },
        {
            name: "Disaster Risk Reduction Cell",
            slug: "drr-cell",
            type: "Cell",
            posts: [
                { bs: "05", postName: "Naib Qasid / Peon", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "07", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "12", postName: "Stenotypist", qualification: "Intermediate + shorthand & 40 wpm typing", ageLimit: "18–30" },
                { bs: "13", postName: "Disaster Management Assistant", qualification: "Bachelor’s in Environmental Sciences", ageLimit: "22–35" },
                { bs: "14", postName: "Field Officer", qualification: "Master’s in Disaster Management", ageLimit: "25–40" },
                { bs: "15", postName: "Assistant Director (DRR)", qualification: "Master’s + 2 yrs experience", ageLimit: "28–45" },
                { bs: "16", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "17", postName: "Director (DRR Cell)", qualification: "Head of cell cadre", ageLimit: "35–60" },
                { bs: "18", postName: "Additional Secretary (DRR)", qualification: "Head of cadre", ageLimit: "40–65" },
                { bs: "19", postName: "Joint Secretary (SAFR)", qualification: "Head of service", ageLimit: "45–70" },
                { bs: "20", postName: "Secretary (SAFR)", qualification: "Head of SAFR ministry", ageLimit: "50–70" },
                { bs: "21", postName: "Chief Secretary (SAFR)", qualification: "Head of service", ageLimit: "60–70" },
                { bs: "22", postName: "Federal Secretary (SAFR)", qualification: "Head of service", ageLimit: "60–70" },
            ],
        },
    ],
};
