import type { Ministry } from "./types";

export const waterResources: Ministry = {
    name: "Ministry of Water Resources",
    slug: "water-resources",
    departments: [
        {
            name: "Indus River System Authority (IRSA)",
            slug: "irsa",
            type: "Authority",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid driving licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Telephone Operator", qualification: "Intermediate; relevant training", ageLimit: "18–30" },
                { bs: "07", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "08", postName: "Survey Assistant", qualification: "Intermediate; basic surveying skills", ageLimit: "18–30" },
                { bs: "09", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "10", postName: "Hydraulic Instructor", qualification: "Diploma in Hydraulic Technology", ageLimit: "18–30" },
                { bs: "11", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer literacy", ageLimit: "18–30" },
                { bs: "12", postName: "Technical Officer", qualification: "Bachelor’s in Civil/Water Resources Engineering", ageLimit: "22–35" },
                { bs: "13", postName: "Assistant Director (Technical)", qualification: "Master’s in Water Resources/Engineering", ageLimit: "25–40" },
                { bs: "14", postName: "Research Officer", qualification: "Master’s + research experience", ageLimit: "28–45" },
                { bs: "15", postName: "Deputy Director (Monitoring)", qualification: "Senior service grade", ageLimit: "30–50" },
                { bs: "16", postName: "Director (IRSA)", qualification: "Head of authority cadre", ageLimit: "35–60" },
                { bs: "17", postName: "Additional Secretary (Water Resources)", qualification: "Federal Secretariat grade", ageLimit: "40–65" },
                { bs: "18", postName: "Member IRSA Board", qualification: "Head of service", ageLimit: "45–70" },
                { bs: "19", postName: "Chairman IRSA", qualification: "Head of authority", ageLimit: "50–70" },
                { bs: "20", postName: "Federal Secretary (Water Resources)", qualification: "Head of service", ageLimit: "55–70" },
                { bs: "21", postName: "Secretary Planning & Dev (ex-officio)", qualification: "Head of planning service", ageLimit: "55–70" },
                { bs: "22", postName: "Minister for Water Resources", qualification: "Elected official", ageLimit: "30–70" },
            ],
        },
        {
            name: "Pakistan Water and Power Development Authority (WAPDA)",
            slug: "wapda",
            type: "Authority",
            posts: [
                { bs: "01", postName: "Peon / Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; valid licence", ageLimit: "18–30" },
                { bs: "05", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "06", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "07", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "08", postName: "Stenotypist", qualification: "Intermediate + shorthand", ageLimit: "18–30" },
                { bs: "09", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "10", postName: "Junior Engineer", qualification: "B.Sc in Electrical/Civil Engineering", ageLimit: "22–35" },
                { bs: "11", postName: "Assistant Engineer", qualification: "B.Sc + training", ageLimit: "25–40" },
                { bs: "12", postName: "Executive Engineer", qualification: "B.Sc + 5 yrs experience", ageLimit: "28–50" },
                { bs: "13", postName: "Superintending Engineer", qualification: "Senior service grade", ageLimit: "30–55" },
                { bs: "14", postName: "Chief Engineer", qualification: "Head of technical cadre", ageLimit: "35–60" },
                { bs: "15", postName: "General Manager", qualification: "Executive grade", ageLimit: "40–65" },
                { bs: "16", postName: "Managing Director", qualification: "Head of Authority", ageLimit: "45–70" },
                { bs: "17", postName: "Member for Water Sector", qualification: "Federal Secretariat grade", ageLimit: "50–70" },
                { bs: "18", postName: "Additional Federal Secretary (Water)", qualification: "Head of service", ageLimit: "55–70" },
                { bs: "19", postName: "Federal Secretary (Water Resources)", qualification: "Head of service", ageLimit: "60–75" },
                { bs: "20", postName: "Minister for Water Resources", qualification: "Elected official", ageLimit: "30–70" },
            ],
        },
        {
            name: "Office of Pakistan Commissioner for Indus Waters",
            slug: "indus-commissioner",
            type: "Office",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "05", postName: "Telephone Operator", qualification: "Intermediate; training", ageLimit: "18–30" },
                { bs: "06", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "07", postName: "Upper Division Clerk (UDC)", qualification: "Intermediate; computer skills", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand", ageLimit: "18–30" },
                { bs: "10", postName: "Technical Assistant", qualification: "Diploma in Civil/Electrical Engineering", ageLimit: "22–35" },
                { bs: "11", postName: "Assistant Director (Indus Water)", qualification: "Master’s in Water Resources", ageLimit: "25–45" },
                { bs: "12", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–60" },
                { bs: "13", postName: "Director", qualification: "Head of office cadre", ageLimit: "35–65" },
                { bs: "14", postName: "Additional Federal Secretary (Water)", qualification: "Head of service", ageLimit: "55–70" },
                { bs: "15", postName: "Federal Secretary (Water Resources)", qualification: "Head of service", ageLimit: "60–75" },
            ],
        },
        {
            name: "Federal Flood Commission (FFC)",
            slug: "ffc",
            type: "Commission",
            posts: [
                { bs: "01", postName: "Naib Qasid", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "02", postName: "Chowkidar", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "03", postName: "Mali", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "04", postName: "Driver", qualification: "Primary pass; licence", ageLimit: "18–30" },
                { bs: "05", postName: "Sweeper", qualification: "Primary pass", ageLimit: "18–25" },
                { bs: "06", postName: "Dispatcher", qualification: "Intermediate; communication skills", ageLimit: "18–30" },
                { bs: "07", postName: "Lower Division Clerk (LDC)", qualification: "Matric; typing 30 wpm", ageLimit: "18–30" },
                { bs: "08", postName: "Data Entry Operator", qualification: "Intermediate; typing 35 wpm", ageLimit: "18–30" },
                { bs: "09", postName: "Stenotypist", qualification: "Intermediate + shorthand", ageLimit: "18–30" },
                { bs: "10", postName: "Surveyor", qualification: "Diploma in Surveying", ageLimit: "22–35" },
                { bs: "11", postName: "Assistant Director (Flood Monitoring)", qualification: "Master’s in Civil Engineering", ageLimit: "25–45" },
                { bs: "12", postName: "Deputy Director", qualification: "Senior service grade", ageLimit: "30–60" },
                { bs: "13", postName: "Director", qualification: "Head of commission cadre", ageLimit: "35–65" },
                { bs: "14", postName: "Additional Secretary (Water)", qualification: "Head of service", ageLimit: "55–70" },
                { bs: "15", postName: "Federal Secretary (Water Resources)", qualification: "Head of service", ageLimit: "60–75" },
            ],
        },
    ],
};
